In [5]:
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
import numpy as np
%matplotlib qt5

In [3]:
### NEW RESULTS!
# All results here are in voxels.

# Total length, Tortousity, bbox volume, turning points
Agamodon_size = 0.012
Agamodon =  [1200.5356998341917*Agamodon_size, 2.89348500744396, 14984260.254190216*Agamodon_size*Agamodon_size*Agamodon_size, 13]
Agamodon_manual = [1356.2911381721497*Agamodon_size, 3.1530881694830684, 18250594.0*Agamodon_size*Agamodon_size*Agamodon_size, 15]

Angustifrons_size = 0.028
Angustifrons = [597.3946509606242*Angustifrons_size, 3.7675408599067506, 3370866.0159863895*Angustifrons_size*Angustifrons_size*Angustifrons_size, 9]
Angustifrons_manual = [572.4312201738358*Angustifrons_size, 3.514732840401786, 3788029.8*Angustifrons_size*Angustifrons_size*Angustifrons_size, 10]

Baika_size = 0.010
Baika  = [830.6992359371347*Baika_size, 4.896175032812801, 5440226.53106542*Baika_size*Baika_size*Baika_size, 8]
Baika_manual = [781.0751061439514*Baika_size, 4.141121724808253, 3597752.0*Baika_size*Baika_size*Baika_size, 7]

# Bipes is good
Bipes_size = 0.012
Bipes = [770.9809656921935*Bipes_size, 3.3399981755186094, 2141760.3131905585*Bipes_size*Bipes_size*Bipes_size, 12]
Bipes_manual = [737.4714935421944*Bipes_size, 4.491450962607393, 2054826.8*Bipes_size*Bipes_size*Bipes_size, 9]

data = [Agamodon, Angustifrons, Baika, Bipes]
data_manual = [Agamodon_manual, Angustifrons_manual, Baika_manual, Bipes_manual]

In [14]:
# Convert data to numpy array
data_array = np.array(data)

# Transpose the array
data_transposed = data_array.T

np.set_printoptions(precision=3, suppress=True)

# Calculate the covariance matrix
cov_matrix = np.cov(data_transposed)
print(cov_matrix)

import seaborn as sns
import matplotlib.pyplot as plt
import pandas as pd

# Define the observation names
observations = ['Total length', 'Tortousity', 'bbox volume', 'turning points']

# Convert the covariance matrix to a DataFrame
cov_df = pd.DataFrame(cov_matrix, columns=observations, index=observations)

# Create a heatmap
sns.heatmap(cov_df, annot=True, fmt='g')

# Show the plot
plt.show()

[[  16.402   -1.689  120.989    1.345]
 [  -1.689    0.738   -4.453   -1.883]
 [ 120.989   -4.453 1072.457  -18.104]
 [   1.345   -1.883  -18.104    5.667]]


In [10]:
from sklearn.decomposition import PCA
# Your data

# Create a PCA object
pca = PCA(n_components=2)

# Fit and transform the data to the first two principal components
data_pca = pca.fit_transform(data)
data_manual_pca = pca.fit_transform(data_manual)

# Calculate the sum of explained variance
explained_variance_sum = sum(pca.explained_variance_ratio_)

# Create a new figure
fig = plt.figure()

# Add a 2D subplot
ax = fig.add_subplot(111)

# Plot each point in its own color and bigger size
ax.scatter(*data_pca[0], color='r', label='Agamodon Anguliceps', s=100)
ax.scatter(*data_pca[1], color='g', label='Angustifrons', s=100)
ax.scatter(*data_pca[2], color='b', label='Baika Africana', s=100)
ax.scatter(*data_pca[3], color='y', label='Bipes Tridactylus', s=100)
ax.scatter(*data_manual_pca[0], color='r', label='Agamodon (manual)', s=100, marker='*')
ax.scatter(*data_manual_pca[1], color='g', label='Angustifrons (manual)', s=100, marker='*')
ax.scatter(*data_manual_pca[2], color='b', label='Baika (manual)', s=100, marker='*')
ax.scatter(*data_manual_pca[3], color='y', label='Bipes (manual)', s=100, marker='*')

# Add a legend
ax.legend(bbox_to_anchor=(0.5, -0.4), loc='upper center', ncol=4, fontsize='small')


# Set equal aspect ratio
ax.set_aspect('equal')

# Set x and y limits with some padding
padding = 5  # Change this value to add more or less padding
plt.xlim(min(data_pca[:, 0].min(), data_manual_pca[:, 0].min()) - padding, max(data_pca[:, 0].max(), data_manual_pca[:, 0].max()) + padding)
plt.ylim(min(data_pca[:, 1].min(), data_manual_pca[:, 1].min()) - padding, max(data_pca[:, 1].max(), data_manual_pca[:, 1].max()) + padding)


# Set x and y labels
ax.set_xlabel('PC1')
ax.set_ylabel('PC2')

# Set title with sum of explained variance
ax.set_title(f'Plot of characteristics in PCA-space (Explained variance: {explained_variance_sum:.5f})')
plt.grid(True)

# Show the plot
plt.show()

In [21]:
from sklearn.svm import SVC
from sklearn.decomposition import PCA
from sklearn.preprocessing import LabelEncoder
import numpy as np

# Your data and labels
labels = ['Agamodon', 'Angustifrons', 'Baika', 'Bipes', 'Agamodon', 'Angustifrons', 'Baika', 'Bipes']

# Create a LabelEncoder object
le = LabelEncoder()

# Fit and transform the labels to integers
labels_encoded = le.fit_transform(labels)

# Concatenate data and data_manual
all_data = np.concatenate((data, data_manual), axis=0)

# Create a PCA object
pca = PCA(n_components=2)

# Fit and transform the data to the first two principal components
all_data_pca = pca.fit_transform(all_data)

# Create a SVM classifier
clf = SVC(kernel='linear')

# Fit the classifier on the all data
clf.fit(all_data_pca, labels_encoded)

# Create a grid to evaluate model
x_min, x_max = all_data_pca[:, 0].min() - 1, all_data_pca[:, 0].max() + 1
y_min, y_max = all_data_pca[:, 1].min() - 1, all_data_pca[:, 1].max() + 1
xx, yy = np.meshgrid(np.arange(x_min, x_max, 0.02),
                     np.arange(y_min, y_max, 0.02))

# Predict on the grid
Z = clf.predict(np.c_[xx.ravel(), yy.ravel()])
Z = Z.reshape(xx.shape)

# Create a new figure
fig = plt.figure()

# Add a 2D subplot
ax = fig.add_subplot(111)

# Plot the decision boundaries
ax.contourf(xx, yy, Z, alpha=0.8)

# Plot each point in its own color and bigger size
for i, label in enumerate(le.classes_):
    ax.scatter(all_data_pca[labels_encoded==i, 0], all_data_pca[labels_encoded==i, 1], label=label, s=100)

# Add a legend
ax.legend(bbox_to_anchor=(0.5, -0.4), loc='upper center', ncol=4, fontsize='small')

# Set equal aspect ratio
ax.set_aspect('equal')

# Set x and y labels
ax.set_xlabel('PC1')
ax.set_ylabel('PC2')

# Set title
ax.set_title('SVM Classification in PCA-space')

# Show the plot
plt.show()